# Generated by Django 3.2.18 on 2023-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroke',
            name='stroke_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
