# Generated by Django 3.2.18 on 2023-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_stroke_stroke_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_code', models.IntegerField(primary_key=True, serialize=False)),
                ('diet_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
