# Generated by Django 3.2.18 on 2023-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20230314_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='recommend_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='recommend_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
