# Generated by Django 3.2.18 on 2023-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20230314_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stroke',
            name='ever_married',
        ),
        migrations.AddField(
            model_name='stroke',
            name='gender',
            field=models.CharField(choices=[('Male', 0), ('Female', 1)], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke',
            name='work_type',
            field=models.CharField(choices=[('Private', 0), ('Self Employed', 1), ('Government Job', 2)], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='avg_glucose_level',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='heart_disease',
            field=models.CharField(choices=[('Have heart diseases', 1), ('Not have heart diseases', 0)], max_length=50),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='hypertension',
            field=models.CharField(choices=[('Have hypertension', 1), ('Not have hypertension', 0)], max_length=50),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
