# Generated by Django 3.2.18 on 2023-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_alter_diet_stroke_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='work_type',
            field=models.CharField(choices=[(0, 'Private'), (1, 'Self Employed'), (2, 'Government Job')], max_length=20),
        ),
    ]
