# Generated by Django 3.2.18 on 2023-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_auto_20230321_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='heart_disease',
            field=models.CharField(choices=[(1, 'Have heart diseases'), (0, 'Not have heart diseases')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='hypertension',
            field=models.CharField(choices=[(1, 'Have hypertension'), (0, 'Not have hypertension')], max_length=50),
        ),
    ]
