# Generated by Django 3.2.18 on 2023-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_auto_20230321_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='heart_disease',
            field=models.IntegerField(choices=[(1, 'Have heart diseases'), (0, 'Not have heart diseases')]),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='hypertension',
            field=models.IntegerField(choices=[(1, 'Have hypertension'), (0, 'Not have hypertension')]),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='work_type',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Self Employed'), (2, 'Government Job')]),
        ),
    ]
