# Generated by Django 3.2.18 on 2023-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_auto_20230321_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='stroke_id',
            field=models.ManyToManyField(to='predict.Stroke'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='avg_glucose_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='result',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='weight',
            field=models.FloatField(),
        ),
    ]
