# Generated by Django 3.2.18 on 2023-04-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0014_auto_20230321_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='stroke_id',
        ),
        migrations.RemoveField(
            model_name='stroke',
            name='recommend_one',
        ),
        migrations.RemoveField(
            model_name='stroke',
            name='recommend_two',
        ),
        migrations.RemoveField(
            model_name='stroke_diet_map',
            name='diet_one',
        ),
        migrations.RemoveField(
            model_name='stroke_diet_map',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='stroke_diet_map',
            name='id',
        ),
        migrations.AddField(
            model_name='stroke',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.diet'),
        ),
        migrations.AddField(
            model_name='stroke_diet_map',
            name='bmi_from',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke_diet_map',
            name='bmi_to',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke_diet_map',
            name='case_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke_diet_map',
            name='diet_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.diet'),
        ),
    ]
