# Generated by Django 3.2.18 on 2023-06-16 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0016_stroke_result_proba'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroke',
            name='patient_code',
            field=models.IntegerField(choices=[(1, 'Other'), (0, 'Me')], null=True),
        ),
        migrations.CreateModel(
            name='Live_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
